apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kuber-crud-app.name" . }}-secret
type: Opaque
data:
  DB_USER: {{ .Values.database.user | b64enc | quote }}
  DB_PASSWORD: {{ .Values.database.password | b64enc | quote }}
